package com.project.TradingWebApp.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.math.BigDecimal;

@Entity
@Data
/**
 * Represents a Wallet entity, used to manage the financial balance of each user within the trading application.
 * This entity stores the current balance of a user's wallet, which is used for trading activities such as buying and selling assets.
 * Each user is associated with one wallet, maintaining a one-to-one relationship.
 */
public class Wallet {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    /**
     * The unique identifier for the wallet.
     * This is a Long type and is automatically generated by the database as the primary key.
     * `GenerationType.IDENTITY` indicates that the database is responsible for generating unique, sequential IDs.
     */
    private Long id;

    @OneToOne
    /**
     * The UserEntity associated with this wallet.
     * Establishes a one-to-one relationship with the UserEntity, meaning each user has exactly one wallet.
     * This field links the wallet to its owner, the user, allowing retrieval of a user's wallet and vice versa.
     */
    private UserEntity user;

    /**
     * The current balance of the wallet.
     * Stored as a BigDecimal to ensure precision for financial transactions and prevent issues with floating-point arithmetic.
     * Represents the amount of funds available in the user's wallet for trading and other transactions.
     */
    private BigDecimal balance;
}